import { StyleSheet } from "react-native";
import { colors } from "@/src/theme/colors";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  logo: { marginBottom: 38 },
  logoCompact: { flexDirection: "row", alignItems: "baseline", gap: 5 },
  logoText: { fontSize: 29, fontWeight: "900", letterSpacing: 1.5, color: colors.primary },
  logoSub: { fontSize: 9, fontWeight: "800", letterSpacing: 2.8, color: colors.muted },
  loginContent: { flexGrow: 1, padding: 26, justifyContent: "center" },
  loginTop: { marginBottom: 10 },
  loginTitle: { fontSize: 32, fontWeight: "900", color: colors.text, marginBottom: 9 },
  loginSubtitle: { color: colors.textSoft, fontSize: 15, lineHeight: 22, maxWidth: 350, marginBottom: 25 },
  formCard: { backgroundColor: colors.white, borderRadius: 22, padding: 21, borderWidth: 1, borderColor: colors.border },
  inputLabel: { fontSize: 12, fontWeight: "800", color: colors.text, marginBottom: 8, marginTop: 4 },
  inputWrap: { minHeight: 52, borderWidth: 1, borderColor: colors.border, borderRadius: 13, backgroundColor: colors.white, flexDirection: "row", alignItems: "center", paddingHorizontal: 14, gap: 10, marginBottom: 15 },
  input: { flex: 1, height: 50, color: colors.text, fontSize: 15 },
  forgotButton: { alignSelf: "flex-end", marginTop: -3, marginBottom: 19 },
  linkText: { color: colors.primary, fontSize: 13, fontWeight: "800" },
  primaryButton: { height: 53, borderRadius: 13, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center", marginTop: 2 },
  primaryButtonText: { color: colors.white, fontSize: 15, fontWeight: "900" },
  outlineButton: { height: 52, borderRadius: 13, borderWidth: 1.5, borderColor: colors.primary, alignItems: "center", justifyContent: "center" },
  outlineButtonText: { color: colors.primary, fontSize: 15, fontWeight: "900" },
  dividerRow: { flexDirection: "row", alignItems: "center", gap: 10, marginVertical: 18 },
  divider: { height: 1, backgroundColor: colors.border, flex: 1 },
  dividerText: { color: colors.muted, fontSize: 12, fontWeight: "700" },
  loginFooter: { textAlign: "center", color: colors.muted, fontSize: 11, marginTop: 24 },
  pageContent: { padding: 21, paddingBottom: 45 },
  pageTitle: { fontSize: 28, fontWeight: "900", color: colors.text, marginTop: 6, marginBottom: 7 },
  pageSubtitle: { color: colors.textSoft, fontSize: 14, lineHeight: 21, marginBottom: 22 },
  backButton: { flexDirection: "row", alignItems: "center", gap: 2, marginBottom: 18 },
  backText: { color: colors.primary, fontWeight: "800", fontSize: 14 },
  homeContent: { padding: 18, paddingBottom: 40 },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 19 },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 11 },
  headerNotification: { width: 40, height: 40, borderRadius: 13, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" },
  notificationDot: { position: "absolute", width: 7, height: 7, borderRadius: 5, backgroundColor: colors.danger, right: 8, top: 7 },
  headerAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" },
  headerAvatarText: { color: colors.white, fontWeight: "900" },
  heroCard: { backgroundColor: colors.primary, borderRadius: 22, padding: 21, minHeight: 137, flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 22 },
  heroEyebrow: { color: "#B9CCE1", fontSize: 10, fontWeight: "900", letterSpacing: 1.5, marginBottom: 5 },
  heroContract: { color: colors.white, fontSize: 24, fontWeight: "900", marginBottom: 10 },
  activePill: { alignSelf: "flex-start", backgroundColor: colors.successSoft, borderRadius: 20, paddingVertical: 6, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", gap: 6 },
  activeDot: { width: 7, height: 7, borderRadius: 5, backgroundColor: colors.success },
  activeText: { color: colors.success, fontSize: 11, fontWeight: "900" },
  heroIcon: { width: 64, height: 64, borderRadius: 20, backgroundColor: colors.white, alignItems: "center", justifyContent: "center" },
  sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12, marginTop: 2 },
  sectionTitle: { fontSize: 18, fontWeight: "900", color: colors.text },
  sectionAction: { color: colors.primary, fontSize: 12, fontWeight: "900" },
  summaryGrid: { flexDirection: "row", gap: 11, marginBottom: 23 },
  summaryCard: { flex: 1, backgroundColor: colors.white, borderRadius: 17, padding: 15, borderWidth: 1, borderColor: colors.border, minHeight: 116 },
  summaryIcon: { width: 35, height: 35, borderRadius: 10, backgroundColor: colors.background, alignItems: "center", justifyContent: "center", marginBottom: 9 },
  summaryNumber: { fontSize: 24, fontWeight: "900", color: colors.text },
  summaryLabel: { color: colors.muted, fontSize: 11, marginTop: 2 },
  invoiceCard: { backgroundColor: colors.white, borderRadius: 16, padding: 14, marginBottom: 10, flexDirection: "row", alignItems: "center", gap: 11, borderWidth: 1, borderColor: colors.border },
  invoiceFeatured: { borderColor: "#C9D8E8", padding: 16 },
  invoiceIcon: { width: 43, height: 43, borderRadius: 13, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" },
  invoiceIconFeatured: { width: 48, height: 48, borderRadius: 14 },
  invoiceTitle: { fontSize: 14, fontWeight: "900", color: colors.text },
  invoiceMeta: { fontSize: 11, color: colors.muted, marginTop: 4 },
  invoiceRight: { alignItems: "flex-end" },
  invoiceAmount: { fontSize: 13, fontWeight: "900", color: colors.text },
  openText: { color: colors.warning, fontSize: 10, fontWeight: "900", marginTop: 3 },
  paidText: { color: colors.success, fontSize: 10, fontWeight: "900", marginTop: 3 },
  totalBar: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 3, marginTop: -1, marginBottom: 24 },
  totalLabel: { color: colors.textSoft, fontSize: 12, fontWeight: "700" },
  totalValue: { color: colors.text, fontSize: 13, fontWeight: "900" },
  quickCard: { backgroundColor: colors.white, borderRadius: 16, padding: 15, marginBottom: 10, flexDirection: "row", alignItems: "center", gap: 12, borderWidth: 1, borderColor: colors.border },
  quickIcon: { width: 44, height: 44, borderRadius: 13, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" },
  quickTitle: { fontSize: 14, fontWeight: "900", color: colors.text },
  quickSubtitle: { color: colors.muted, fontSize: 11, marginTop: 3 },
  segment: { backgroundColor: "#E9EDF2", borderRadius: 13, padding: 4, flexDirection: "row", marginBottom: 18 },
  segmentItem: { flex: 1, height: 43, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  segmentActive: { backgroundColor: colors.white, shadowColor: "#000", shadowOpacity: 0.04, shadowRadius: 5, elevation: 1 },
  segmentText: { color: colors.muted, fontSize: 12, fontWeight: "800" },
  segmentTextActive: { color: colors.primary },
  emptyCard: { backgroundColor: colors.white, borderRadius: 18, padding: 28, alignItems: "center", borderWidth: 1, borderColor: colors.border, marginTop: 10 },
  emptyIcon: { width: 54, height: 54, borderRadius: 27, backgroundColor: colors.successSoft, alignItems: "center", justifyContent: "center", marginBottom: 12 },
  emptyTitle: { fontSize: 16, fontWeight: "900", color: colors.text },
  emptyText: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 6 },
  secureNote: { marginTop: 12, padding: 14, borderRadius: 12, backgroundColor: colors.primarySoft },
  secureNoteText: { color: colors.primary, fontSize: 11, lineHeight: 17, textAlign: "center" },
  contractStatusCard: { backgroundColor: colors.white, borderRadius: 18, padding: 17, flexDirection: "row", alignItems: "center", gap: 13, borderWidth: 1, borderColor: colors.border, marginBottom: 12 },
  contractStatusIcon: { width: 51, height: 51, borderRadius: 15, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" },
  contractStatusLabel: { color: colors.muted, fontSize: 9, fontWeight: "900", letterSpacing: 1 },
  contractStatusValue: { color: colors.success, fontSize: 20, fontWeight: "900", marginTop: 2 },
  bigStatusDot: { width: 10, height: 10, borderRadius: 7, backgroundColor: colors.success },
  detailCard: { backgroundColor: colors.white, borderRadius: 18, padding: 17, borderWidth: 1, borderColor: colors.border },
  detailRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 13 },
  detailIcon: { width: 42, height: 42, borderRadius: 12, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" },
  detailLabel: { color: colors.muted, fontSize: 11, marginBottom: 4 },
  detailValue: { color: colors.text, fontSize: 14, fontWeight: "800", lineHeight: 19 },
  contractInfoBox: { flexDirection: "row", gap: 9, backgroundColor: colors.primarySoft, padding: 14, borderRadius: 13, marginTop: 14 },
  infoText: { flex: 1, color: colors.textSoft, fontSize: 11, lineHeight: 17 },
  profileCard: { backgroundColor: colors.white, borderRadius: 19, alignItems: "center", padding: 24, borderWidth: 1, borderColor: colors.border, marginBottom: 13 },
  avatar: { width: 72, height: 72, borderRadius: 36, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center", marginBottom: 11 },
  avatarText: { color: colors.white, fontSize: 27, fontWeight: "900" },
  profileName: { color: colors.text, fontSize: 18, fontWeight: "900" },
  profileCpf: { color: colors.muted, fontSize: 11, marginTop: 4 },
  profileMenu: { backgroundColor: colors.white, borderRadius: 18, paddingVertical: 4, borderWidth: 1, borderColor: colors.border },
  profileItem: { flexDirection: "row", alignItems: "center", padding: 14, gap: 12, borderBottomWidth: 1, borderBottomColor: colors.border },
  profileItemIcon: { width: 40, height: 40, borderRadius: 12, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" },
  profileItemTitle: { color: colors.text, fontSize: 13, fontWeight: "900" },
  profileItemSubtitle: { color: colors.muted, fontSize: 10, marginTop: 3 },
  logoutButton: { marginTop: 14, height: 50, backgroundColor: colors.dangerSoft, borderRadius: 13, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  logoutText: { color: colors.danger, fontWeight: "900", fontSize: 13 },
  version: { textAlign: "center", color: colors.muted, fontSize: 10, marginTop: 20 },
  infoBox: { flexDirection: "row", alignItems: "center", gap: 9, padding: 13, backgroundColor: colors.primarySoft, borderRadius: 13, marginTop: 2, marginBottom: 17 },
  centerButton: { alignItems: "center", padding: 18 },
  invoiceDetailHero: { backgroundColor: colors.white, borderRadius: 20, alignItems: "center", padding: 25, borderWidth: 1, borderColor: colors.border, marginBottom: 12 },
  invoiceDetailIcon: { width: 58, height: 58, borderRadius: 18, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center", marginBottom: 11 },
  invoiceDetailReference: { color: colors.textSoft, fontSize: 13, fontWeight: "800" },
  invoiceDetailAmount: { color: colors.text, fontSize: 31, fontWeight: "900", marginTop: 5, marginBottom: 11 },
  detailStatusPill: { borderRadius: 20, paddingHorizontal: 12, paddingVertical: 6 },
  openPill: { backgroundColor: colors.warningSoft },
  paidPill: { backgroundColor: colors.successSoft },
  detailStatusText: { fontSize: 11, fontWeight: "900" },
  infoRow: { paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: colors.border, flexDirection: "row", justifyContent: "space-between", gap: 15 },
  infoRowLabel: { color: colors.muted, fontSize: 12 },
  infoRowValue: { color: colors.text, fontSize: 12, fontWeight: "800", textAlign: "right", flex: 1 },
  payButton: { height: 53, borderRadius: 13, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 9, marginTop: 13 },
  payButtonText: { color: colors.white, fontSize: 14, fontWeight: "900" },
  detailFooter: { color: colors.muted, textAlign: "center", fontSize: 10, lineHeight: 16, marginTop: 15 },
});
